tbl_dados_das_linhas = [
    {"field": "dia", "headerName": "DIA", "minWidth": 300},
    {"field": "vec_num_id", "headerName": "VEÍCULO", "minWidth": 200},
    {"field": "encontrou_numero_linha", "headerName": "LINHA", "minWidth": 200},
    {
        "field": "encontrou_sentido_linha",
        "headerName": "SENTIDO",
        "filter": "agNumberColumnFilter",
        "maxWidth": 230,
        "type": ["text"],
    },
    {
        "field": "CONSUMO_POR_KM",
        "headerName": "KM/L",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 230,
        "type": ["numericColumn"],
    },
    {
        "field": "CONSUMO_POR_KM_VEICULO",
        "headerName": "MÉDIA VEICULO",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "type": ["numericColumn"],
    },
    {
        "field": "DIFERENCA_CONSUMO_KM-VEICULO_",
        "headerName": "DIFERENÇA KM/L - MÉDIA VEICULO",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "type": ["numericColumn"],
    },
    {
        "field": "CONSUMO_POR_KM_LINHA",
        "headerName": "MEDIA LINHA",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "type": ["numericColumn"],
    },
    {
        "field": "DIFERENCA_CONSUMO_KM-LINHA",
        "headerName": "DIFERENÇA KM/L - MÉDIA LINHA",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "type": ["numericColumn"],
    },
]