tbl_dados_das_linhas = [
    {"field": "DESCRICAO DO SERVICO", "headerName": "DIA", "minWidth": 300},
    {"field": "TOTAL_OS", "headerName": "VEÍCULO", "minWidth": 200},
    {"field": "PERC_RETRABALHO", "headerName": "LINHA", "minWidth": 200, "valueFormatter": {"function": "params.value + '%'"},},
    {
        "field": "PERC_CORRECAO_PRIMEIRA",
        "headerName": "SENTIDO",
        "filter": "agNumberColumnFilter",
        "maxWidth": 230,
        "valueFormatter": {"function": "params.value + '%'"},
        "type": ["numericColumn"],
    },
    {
        "field": "QUANTIDADE DE PECAS",
        "headerName": "KM/L",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 230,
        "type": ["numericColumn"],
    },
    {
        "field": "VALOR_",
        "headerName": "MÉDIA VEICULO",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "type": ["numericColumn"],
        "valueFormatter": {"function": "'R$' + Number(params.value).toFixed(2).toLocaleString()"},
    },
    {
        "field": "TOTAL_GASTO_RETRABALHO_",
        "headerName": "DIFERENÇA KM/L - MÉDIA VEICULO",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "type": ["numericColumn"],
        "valueFormatter": {"function": "'R$' + Number(params.value).toFixed(2).toLocaleString()"},
    },
    {
        "field": "TOTAL_GASTO_RETRABALHO_",
        "headerName": "MEDIA LINHA",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "type": ["numericColumn"],
        "valueFormatter": {"function": "'R$' + Number(params.value).toFixed(2).toLocaleString()"},
    },
    {
        "field": "TOTAL_GASTO_RETRABALHO_",
        "headerName": "DIFERENÇA KM/L - MÉDIA LINHA",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "type": ["numericColumn"],
        "valueFormatter": {"function": "'R$' + Number(params.value).toFixed(2).toLocaleString()"},
    },
]