#!/usr/bin/env python
# coding: utf-8

# Arquivo que centraliza as tabelas utilizadas na página home

# Tabela Top OS de Retrabalho
tbl_top_os_geral_retrabalho = [
    {
        "field": "DESCRICAO DA OFICINA",
        "headerName": "OFICINA",
        "pinned": "left",
        "minWidth": 200,
    },
    {"field": "DESCRICAO DA SECAO", "headerName": "SEÇÃO", "minWidth": 200},
    {"field": "DESCRICAO DO SERVICO", "headerName": "SERVIÇO", "minWidth": 250},
    {
        "field": "TOTAL_OS",
        "headerName": "TOTAL DE OS",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "maxWidth": 160,
        "filter": "agNumberColumnFilter",
        "type": ["numericColumn"],
    },
    {
        "field": "PERC_RETRABALHO",
        "headerName": "% RETRABALHOS",
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "valueFormatter": {"function": "params.value.toLocaleString() + '%'"},
        "type": ["numericColumn"],
    },
    {
        "field": "PERC_CORRECAO_PRIMEIRA",
        "headerName": "% CORREÇÕES DE PRIMEIRA",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "valueFormatter": {"function": "params.value.toLocaleString() + '%'"},
        "type": ["numericColumn"],
    },
    {
        "field": "TOTAL_PROBLEMA",
        "headerName": "TOTAL DE PROBLEMA",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "type": ["numericColumn"],
    },
    {
        "field": "REL_OS_PROBLEMA",
        "headerName": "REL OS/PROBLEMA",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "maxWidth": 160,
        "valueFormatter": {"function": "params.value.toLocaleString()"},
        "filter": "agNumberColumnFilter",
        "type": ["numericColumn"],
    },
    {
        "field": "NOTA_MEDIA_SINTOMA",
        "headerName": "NOTA MÉDIA SINTOMA",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "maxWidth": 160,
        "valueFormatter": {"function": "params.value.toLocaleString()"},
        "filter": "agNumberColumnFilter",
        "type": ["numericColumn"],
    },
    {
        "field": "NOTA_MEDIA_SOLUCAO",
        "headerName": "NOTA MÉDIA SOLUÇÃO",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "maxWidth": 160,
        "valueFormatter": {"function": "params.value.toLocaleString()"},
        "filter": "agNumberColumnFilter",
        "type": ["numericColumn"],
    },
    {
        "field": "PERC_SINTOMA_COERENTE",
        "headerName": "% OS SINTOMAS COERENTE",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "valueFormatter": {"function": "params.value.toLocaleString() + '%'"},
        "type": ["numericColumn"],
    },
    {
        "field": "PERC_SOLUCAO_COERENTE",
        "headerName": "% OS SOLUÇÃO COERENTE",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "valueFormatter": {"function": "params.value.toLocaleString() + '%'"},
        "type": ["numericColumn"],
    },
]

# Tabela Top OS Colaborador
tbl_top_colaborador_geral_retrabalho = [
    {
        "field": "NOME_COLABORADOR",
        "headerName": "Colaborador",
        "pinned": "left",
    },
    {"field": "ID_COLABORADOR", "headerName": "ID", "filter": "agNumberColumnFilter", "minWidth": 100, "maxWidth": 100},
    {
        "field": "TOTAL_OS",
        "headerName": "TOTAL DE OS",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "type": ["numericColumn"],
    },
    {
        "field": "PERC_RETRABALHO",
        "headerName": "% RETRABALHOS",
        "filter": "agNumberColumnFilter",
        "valueFormatter": {"function": "params.value.toLocaleString() + '%'"},
        "type": ["numericColumn"],
    },
    {
        "field": "PERC_CORRECAO_PRIMEIRA",
        "headerName": "% CORREÇÕES DE PRIMEIRA",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "valueFormatter": {"function": "params.value.toLocaleString() + '%'"},
        "type": ["numericColumn"],
    },
    {
        "field": "TOTAL_PROBLEMA",
        "headerName": "TOTAL DE PROBLEMA",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "maxWidth": 160,
        "filter": "agNumberColumnFilter",
        "type": ["numericColumn"],
    },
    {
        "field": "REL_OS_PROBLEMA",
        "headerName": "REL OS/PROBLEMA",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "valueFormatter": {"function": "params.value.toLocaleString()"},
        "filter": "agNumberColumnFilter",
        "type": ["numericColumn"],
    },
    {
        "field": "NOTA_MEDIA_SOLUCAO",
        "headerName": "NOTA MÉDIA (LLM)",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "maxWidth": 160,
        "valueFormatter": {"function": "params.value.toLocaleString()"},
        "filter": "agNumberColumnFilter",
        "type": ["numericColumn"],
    },
    {
        "field": "PERC_SOLUCAO_COERENTE",
        "headerName": "% SOLUÇÕES COERENTES (LLM)",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "maxWidth": 160,
        "filter": "agNumberColumnFilter",
        "valueFormatter": {"function": "params.value.toLocaleString() + '%'"},
        "type": ["numericColumn"],
    },
]
